import = [
    "~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml",
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/zellij"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[window]
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14
