import = [
    "~/.config/alacritty/themes/themes/moonlight_ii_vscode.toml",
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14
