after-login-command = []
after-startup-command = []
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

[mode.main.binding]
ctrl-shift-comma = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

ctrl-m = 'fullscreen'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-b = 'workspace B'
ctrl-e = 'workspace E'
ctrl-t = 'workspace T'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-b = 'move-node-to-workspace B'
ctrl-shift-e = 'move-node-to-workspace E'
ctrl-shift-t = 'move-node-to-workspace T'

ctrl-tab = 'workspace-back-and-forth'
ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-shift-period = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-shift-h = ['join-with left', 'mode main']
ctrl-shift-j = ['join-with down', 'mode main']
ctrl-shift-k = ['join-with up', 'mode main']
ctrl-shift-l = ['join-with right', 'mode main']

#[[on-window-detected]]
#if.app-id = 'com.brave.Browser'
#run = "move-node-to-workspace B"

#[[on-window-detected]]
#if.app-id = 'org.alacritty'
#run = "move-node-to-workspace T"

#[[on-window-detected]]
#if.app-id = 'com.jetbrains.intellij.ce-EAP'
#run = "move-node-to-workspace E"
